"""fix_dias_laborales_length

Revision ID: 0401bc898787
Revises: 4914e35f7405
Create Date: 2026-06-05 11:20:01.932423
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0401bc898787'
down_revision: Union[str, None] = '4914e35f7405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'dias_laborales',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'dias_laborales',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
