"""add_asistencia_feriados

Revision ID: 32c7109c92c6
Revises: 61746b7e4c2a
Create Date: 2026-06-05 10:33:20.415601
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '32c7109c92c6'
down_revision: Union[str, None] = '61746b7e4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False),
    sa.Column('horas_normales', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('horas_extra', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('es_feriado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencias')
    op.drop_table('feriados')
    # ### end Alembic commands ###
