"""add_edad_empleado

Revision ID: 4914e35f7405
Revises: f766a1231899
Create Date: 2026-06-05 11:15:58.001934
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4914e35f7405'
down_revision: Union[str, None] = 'f766a1231899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('edad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'edad')
    # ### end Alembic commands ###
