"""add_jornada_valor_hora_empleado

Revision ID: 57e7df5953e5
Revises: 32c7109c92c6
Create Date: 2026-06-05 10:35:32.034827
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '57e7df5953e5'
down_revision: Union[str, None] = '32c7109c92c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('horas_jornada', sa.Numeric(precision=4, scale=2), nullable=False))
    op.add_column('empleados', sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'valor_hora')
    op.drop_column('empleados', 'horas_jornada')
    # ### end Alembic commands ###
