"""add_nomina_tables

Revision ID: 61746b7e4c2a
Revises: f0050ab3dbf8
Create Date: 2026-06-05 10:26:47.852921
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '61746b7e4c2a'
down_revision: Union[str, None] = 'f0050ab3dbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_nomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('monto_fijo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('fecha_liquidacion', sa.Date(), nullable=False),
    sa.Column('sueldo_basico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_haberes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deducciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidacion_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos_nomina.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liquidacion_detalle')
    op.drop_table('liquidaciones')
    op.drop_table('conceptos_nomina')
    # ### end Alembic commands ###
