"""add_config_nomina

Revision ID: 65393ca3dfde
Revises: ce8752fb254a
Create Date: 2026-06-05 12:00:04.361930
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '65393ca3dfde'
down_revision: Union[str, None] = 'ce8752fb254a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_nomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_nomina')
    # ### end Alembic commands ###
