"""add_sueldo_mensual_empleado

Revision ID: 6e67fedca4aa
Revises: c1d1161656a6
Create Date: 2026-06-05 10:42:07.302714
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6e67fedca4aa'
down_revision: Union[str, None] = 'c1d1161656a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('sueldo_mensual', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'sueldo_mensual')
    # ### end Alembic commands ###
