"""add_datos_empresa

Revision ID: 761e1a771bab
Revises: b8a4ad62823b
Create Date: 2026-06-05 13:11:28.827487
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '761e1a771bab'
down_revision: Union[str, None] = 'b8a4ad62823b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos_empresa')
    # ### end Alembic commands ###
