"""make_dni_cuil_nullable

Revision ID: 7e6d1ba8ac1b
Revises: 148e4f8983f9
Create Date: 2026-06-05 15:34:46.952165
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7e6d1ba8ac1b'
down_revision: Union[str, None] = '148e4f8983f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('empleados', 'cuil',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'cuil',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('empleados', 'dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
