"""add_adelantos

Revision ID: ba181f47ec6b
Revises: 6e67fedca4aa
Create Date: 2026-06-05 10:51:46.356483
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ba181f47ec6b'
down_revision: Union[str, None] = '6e67fedca4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adelantos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=False),
    sa.Column('periodo_descuento', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adelantos')
    # ### end Alembic commands ###
