"""add_dias_horario_empleado

Revision ID: c1d1161656a6
Revises: 57e7df5953e5
Create Date: 2026-06-05 10:37:17.992787
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c1d1161656a6'
down_revision: Union[str, None] = '57e7df5953e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('dias_laborales', sa.String(length=20), nullable=False))
    op.add_column('empleados', sa.Column('hora_entrada', sa.String(length=5), nullable=False))
    op.add_column('empleados', sa.Column('hora_salida', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'hora_salida')
    op.drop_column('empleados', 'hora_entrada')
    op.drop_column('empleados', 'dias_laborales')
    # ### end Alembic commands ###
