"""add_cierres_y_adelantos_cuotas

Revision ID: ce8752fb254a
Revises: 0401bc898787
Create Date: 2026-06-05 11:50:08.646591
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ce8752fb254a'
down_revision: Union[str, None] = '0401bc898787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('cerrado', sa.Boolean(), nullable=False),
    sa.Column('cerrado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reabierto_por', sa.Integer(), nullable=True),
    sa.Column('fecha_reapertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo')
    )
    op.create_table('cierres_liquidacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('cerrado', sa.Boolean(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adelantos', sa.Column('cuotas', sa.Integer(), nullable=False))
    op.add_column('adelantos', sa.Column('cuotas_descontadas', sa.Integer(), nullable=False))
    op.add_column('adelantos', sa.Column('monto_descontado', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('adelantos', sa.Column('saldo_pendiente', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('adelantos', sa.Column('completado', sa.Boolean(), nullable=False))
    op.drop_column('adelantos', 'periodo_descuento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adelantos', sa.Column('periodo_descuento', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_column('adelantos', 'completado')
    op.drop_column('adelantos', 'saldo_pendiente')
    op.drop_column('adelantos', 'monto_descontado')
    op.drop_column('adelantos', 'cuotas_descontadas')
    op.drop_column('adelantos', 'cuotas')
    op.drop_table('cierres_liquidacion')
    op.drop_table('cierres_asistencia')
    # ### end Alembic commands ###
