"""add_empleados_departamentos_cargos

Revision ID: f0050ab3dbf8
Revises: ca0794285ff8
Create Date: 2026-06-05 10:12:48.961411
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f0050ab3dbf8'
down_revision: Union[str, None] = 'ca0794285ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('cuil', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuil'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleados')
    op.drop_table('departamentos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
